channels:
- defaults
- http://ssb.stsci.edu/astroconda
dependencies:
- django=3.0.3
- flake8=3.8.3
- inflection=0.3.1
- ipython=7.16.1
- jinja2=2.11.2
- jsonschema=3.2.0
- matplotlib=3.2.2
- nodejs=10.13.0
- numpy=1.18.5
- numpydoc=1.1.0
- pandas=1.1.1
- pip=20.2.2
- postgresql=12.2
- psycopg2=2.8.5
- python=3.8.5
- pytest=6.0.1
- pytest-cov=2.10.1
- scipy=1.5.0
- setuptools=49.6.0
- sphinx=3.2.1
- twine=2.0.0
- pip:
  - asdf==2.7.1
  - astropy==4.0.1.post1
  - astroquery==0.4.1
  - authlib==0.15.1
  - bokeh>=1.0,<1.4
  - codecov==2.1.9
  - crds==10.0.0
  - jwedb==0.0.6
  - jwst==0.17.1
  - pysiaf==0.9.0
  - pysqlite3==0.4.3
  - sqlalchemy==1.3.19
  - stsci_rtd_theme==0.0.2
  - git+https://github.com/spacetelescope/jwst_reffiles
