channels:
- defaults
- http://ssb.stsci.edu/astroconda
dependencies:
- astroquery=0.3.7
- bokeh=0.13.9
- django=2.1.1
- flake8=3.5.0
- inflection=0.3.1
- ipython=6.5.0
- jinja2=2.10.3
- jsonschema=2.6.0
- matplotlib=3.0.0
- numpy=1.14.2
- numpydoc=0.9.1
- pandas=0.22.0
- pip=10.0.1
- postgresql=10.5
- psycopg2=2.7.5
- python=3.5.6
- pytest=3.8.1
- pytest-cov=2.7.1
- scipy=1.1.0
- setuptools=40.2.0
- sphinx=2.2.0
- sqlalchemy=1.2.11
- twine=1.11.0
- pip:
  - asdf==2.4.2
  - astropy==2.0.8
  - authlib==0.12.1
  - codecov==2.0.15
  - jwedb>=0.0.6
  - jwst
  - pysiaf==0.5.0
  - pysqlite3==0.4.1
  - stsci_rtd_theme==0.0.2