name: jwqldev
channels:
- defaults
- http://ssb.stsci.edu/astroconda-dev
dependencies:
- astropy=2.0.3
- django=1.11.8
- jwst=0.7.8rc9
- matplotlib=2.1.1
- numpy=1.14.0
- postgresql=9.6.6
- python=3.6.4
- python-dateutil=2.6.1
- sphinx=1.6.6
- sqlalchemy=1.2.0
- pip:
  - sphinx-automodapi==0.7