[project]
name = "jwql"
description = "The James Webb Space Telescope Quicklook Project"
authors = [
  { name = "Matthew Bourque" },
  { name = "Lauren Chambers" },
  { name = "Misty Cracraft" },
  { name = "Mike Engesser" },
  { name = "Mees Fix" },
  { name = "Joe Filippazzo" },
  { name = "Bryan Hilbert" },
]
keywords = ["astronomy", "python"]
classifiers = ["Programming Language :: Python"]
dependencies = [
  "asdf",
  "astropy",
  "astroquery",
  "bandit",
  "bokeh<3",
  "crds",
  "cryptography",
  "django",
  "flake8",
  "inflection",
  "ipython",
  "jinja2",
  "jsonschema",
  "jwst",
  "jwst_reffiles",
  "matplotlib",
  "nodejs",
  "numpy",
  "numpydoc",
  "pandas",
  "psycopg2",
  "pysiaf",
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "pyvo",
  "scipy",
  "sphinx",
  "sphinx_rtd_theme",
  "sqlalchemy",
  "stdatamodels",
  "stsci_rtd_theme",
  "twine",
  "wtforms",
]
dynamic = ["version"]

[project.license]
file = "LICENSE"
content-type = "text/plain"

[build-system]
requires = ["setuptools>=61.2,<=65.5.0", "numpy", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools_scm]
