name: JWQL CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install bandit
      - run: bandit ./jwql/ -c .bandit

  test:
    name: test (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - run: |
            echo "major=$(echo ${{ matrix.python-version }} | head -c 1)" >> $GITHUB_OUTPUT
            echo "minor=$(echo ${{ matrix.python-version }} | tail -c 2)" >> $GITHUB_OUTPUT
        id: python

      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: ./environment_python_${{ steps.python.outputs.major }}_${{ steps.python.outputs.minor }}.yml
          cache-env: true
          cache-downloads: true

      - run: pip install -e .

      - run: conda env export
      
      - uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 5.0
        if: runner.os == 'Linux'

      - run: python -c "import jwql; print('Version ' + jwql.__version__); print('Path ' + jwql.__path__[0])"

      - run: pytest jwql/tests/
